-- ========================================================
-- 아궁진영의 수학교실 : Supabase 데이터베이스 테이블 생성 쿼리
-- Supabase 대시보드 -> SQL Editor에 복사하여 Run(실행)하세요!
-- ========================================================

-- 1. [일차식 덧셈·뺄셈] 학생 점수 테이블 (expression_scores)
CREATE TABLE IF NOT EXISTS public.expression_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    score INT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    accuracy INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) 설정 및 공개 정책 추가
ALTER TABLE public.expression_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read expression_scores" 
ON public.expression_scores 
FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert expression_scores" 
ON public.expression_scores 
FOR INSERT 
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_expression_scores_score 
ON public.expression_scores (score DESC);


-- 2. [일차방정식] 학생 점수 테이블 (student_scores)
CREATE TABLE IF NOT EXISTS public.student_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    score INT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    accuracy INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.student_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read student_scores" 
ON public.student_scores 
FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert student_scores" 
ON public.student_scores 
FOR INSERT 
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_student_scores_score 
ON public.student_scores (score DESC);
