-- ========================================================
-- 아궁진영의 수학교실 : Supabase 데이터베이스 테이블 생성 쿼리
-- Supabase 대시보드 -> SQL Editor에 복사하여 Run 실행하세요!
-- ========================================================

-- 1. 학생 점수 테이블 생성 (student_scores)
CREATE TABLE IF NOT EXISTS public.student_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    score INT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    accuracy INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 읽기/쓰기 권한 설정 (Row Level Security & Policies)
ALTER TABLE public.student_scores ENABLE ROW LEVEL SECURITY;

-- 누구나 리더보드 점수를 조회할 수 있도록 허용하는 정책
CREATE POLICY "Allow public read access" 
ON public.student_scores 
FOR SELECT 
USING (true);

-- 누구나 학생 점수를 등록(INSERT)할 수 있도록 허용하는 정책
CREATE POLICY "Allow public insert access" 
ON public.student_scores 
FOR INSERT 
WITH CHECK (true);

-- 3. 점수 내림차순 검색 성능 최적화를 위한 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_student_scores_score 
ON public.student_scores (score DESC);
